# Generated by Django 4.1.5 on 2023-02-13 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_rename_cat_women_cat_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='women',
            old_name='cat_id',
            new_name='cat',
        ),
    ]
